name: Build QuickMemo (Pynsist)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8]
        qt-framework: [pyqt5, pyside5]
        architecture: [x86, x64]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pynsist
        if [ "${{ matrix.qt-framework }}" = "pyqt5" ]; then
          pip install -r requirements.txt
        else
          pip install -r requirements-pyside5.txt
        fi

    - name: Build installer with pynsist
      run: |
        if [ "${{ matrix.qt-framework }}" = "pyqt5" ]; then
          cp installer-pyqt5.cfg installer.cfg
        else
          cp installer-pyside5.cfg installer.cfg
        fi
        pynsist installer.cfg

    - name: Archive installer
      run: |
        mkdir -p dist
        cp build/nsis/QuickMemoInstaller.exe dist/QuickMemo-${{ matrix.qt-framework }}-${{ matrix.architecture }}.exe

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: QuickMemo-${{ matrix.qt-framework }}-${{ matrix.architecture }}
        path: dist/QuickMemo-${{ matrix.qt-framework }}-${{ matrix.architecture }}.exe