name: Build Windows Executables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.8]
        architecture: [x86, x64]
        include:
          - architecture: x86
            python-arch: 32
            artifact-name: QuickMemo-win32
          - architecture: x64
            python-arch: 64
            artifact-name: QuickMemo-win64

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create assets directory
      run: mkdir assets
    
    - name: Create placeholder icon
      run: |
        # Create a simple placeholder icon (you should replace this with your actual icon)
        echo "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAAdgAAAHYBTnsmCAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAB8SURBVDiNY2AYBYMRMDIyMjAyMjL8//+f4f///wz//v1j+P//P8P///8Z/v//z/D//3+G////M/z//5/h////DP///2f4//8/w////xn+////H4gZGBgYGBkZGRgZGRkYGRkZGBkZGRgZGRkYGRkZGBkZGRgZGRkYGRkZGBkZGRgBANQcD0XqXhQAAAAASUVORK5CYII=" | base64 -d > assets/icon.ico
    
    - name: Build executable
      run: |
        pyinstaller --clean quickmemo.spec
    
    - name: Create release archive
      run: |
        cd dist
        7z a -tzip ../${{ matrix.artifact-name }}.zip QuickMemo.exe
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.artifact-name }}
        path: ${{ matrix.artifact-name }}.zip
        retention-days: 5 